// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlv3RlohqAJE2YWUdAoRVVoAejgkRsrbI',
    appId: '1:883949837120:web:02d8f00b2a23758ed8f8a5',
    messagingSenderId: '883949837120',
    projectId: 'exam-lab-f6df3',
    authDomain: 'exam-lab-f6df3.firebaseapp.com',
    storageBucket: 'exam-lab-f6df3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsUQp7oXmd_OsrISh79z59CzzPkYTcgMU',
    appId: '1:883949837120:android:d5857040468838d4d8f8a5',
    messagingSenderId: '883949837120',
    projectId: 'exam-lab-f6df3',
    storageBucket: 'exam-lab-f6df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXkhbqCkUtE3Opm2xMt32QKznhrfUttY',
    appId: '1:883949837120:ios:085ce3323977a181d8f8a5',
    messagingSenderId: '883949837120',
    projectId: 'exam-lab-f6df3',
    storageBucket: 'exam-lab-f6df3.appspot.com',
    iosClientId: '883949837120-ni4u2nmbnag2gd8rfu10rpobpudia3uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXkhbqCkUtE3Opm2xMt32QKznhrfUttY',
    appId: '1:883949837120:ios:085ce3323977a181d8f8a5',
    messagingSenderId: '883949837120',
    projectId: 'exam-lab-f6df3',
    storageBucket: 'exam-lab-f6df3.appspot.com',
    iosClientId: '883949837120-ni4u2nmbnag2gd8rfu10rpobpudia3uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3',
  );
}
